### ISSUE TITLE
Boolean type

### ISSUE THREAD

**Issue by timkurvers** [devongovett/restructure#12]
Right now I'm using `r.uintx` to represent booleans, but is there a boolean type I may have overlooked?

Not entirely sure about the added benefit, but it would be easier to spot booleans within structs as they would stand out.

**Comment by devongovett** [comment]
There isn't a boolean type currently, but I think that would be a good thing to add.

**Comment by timkurvers** [comment]
Should it be a wrapper of some sorts?

```
r.bool(r.uint32le)
```

**Comment by devongovett** [comment]
yeah. I'd just make another class called `r.Boolean` implementing `decode`, `size`, and `encode`.
